### ISSUE TITLE
Antenna issue and LNA issue

### ISSUE THREAD

**Issue by 32mehmetcakir** [ffgraz/openwrt-wiki#1]
I have tested :)

In generally, except for these issues it is working properly. Issues that need to be improved:

1) Internal Vertical and Horizontal antenna not selectable not work how is it work? 
2) Transmission Power (Tx-Power): max 26dbm country code is BZ ( How up to 27 dbm(Official tp-link firmware up to 27dbm))

Is there testing? 
Write the answer please? 
Thanks..

**Comment by alexlist** [comment]
You filed this issue against the prototype of a wiki page, which seems to be the wrong place.

Please elaborate which version you got from where.

Our initial support for the TL-WA7210N was merged upstream with OpenWRT, so please feel free to file tickets there.

We did not get as far as fixing all the LEDs, PA and polarization switches.

**Comment by 32mehmetcakir** [comment]
Yes, thank you for your attention. I have tested OpenWRT Chaos Calmer 15:05 RC3.

OpenWRT-15:05-RC3-ar71xx-generic-TL-wa7210n-v2-SquashFS-factory.bin
I've tested this version and the developers did two issue a ticket but did not get a return for more than a weeks :(

**Comment by nicoonoclaste** [comment]
Hi.

We aren't the OpenWRT developpers, https://dev.openwrt.org/ is the right place for this.
